# Animates and "pours" each ingredient into the bowl when user clicks
# Animation code generated by claude (4/6/26)
# Prompt: How can I animate an ingredient to pour into a bowl after emitting a 
# clicked signal by rotating around 120 degrees and -120 degrees if its on the left 
@tool
extends Area2D

signal clicked(value)
@export var value := ""
@export var flip_rotation: bool = false
@export var texture: Texture2D:
	set(v):
		texture = v
		if $Sprite2D:
			$Sprite2D.texture = texture

var has_been_clicked = false
var _origin_pos: Vector2
var _origin_rot: float
var bowl_pos = Vector2(590, 130)

func _ready():
	$Sprite2D.texture = texture
	_origin_pos = position
	_origin_rot = rotation

# Checks if the ingredient was clicked by user 
func _input_event(viewport, event, shape_idx):
	if event is InputEventMouseButton and event.pressed:
		if not has_been_clicked:
			has_been_clicked = true
			clicked.emit(value)
			animate()

# Moves ingredient to the bowl while rotating it based on what side of the screen its on
func animate():
	var rot_amount = deg_to_rad(120) if not flip_rotation else deg_to_rad(-120)
	var tween = create_tween()
	tween.tween_property(self, "global_position", bowl_pos, 0.4).set_trans(Tween.TRANS_SINE)
	tween.parallel().tween_property(self, "rotation", _origin_rot + rot_amount, 0.4)
	tween.tween_property(self, "global_position", _origin_pos, 0.3).set_trans(Tween.TRANS_SINE)
	tween.parallel().tween_property(self, "rotation", _origin_rot, 0.3)
